n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
n3 = int(input('Digite mais um número: '))
nt = (n1, n2, n3)
print(f'O maior valor digitado foi: {max(nt)}')
print(f'O menor valor digitado foi: {min(nt)}')